CREATE TABLE `badips` (
  `id` mediumint NOT NULL AUTO_INCREMENT,
  `ip` char(120) NOT NULL,
  `ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1469116 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
